apiVersion: v1
kind: abcd
metadata:
  name: secret-dotfiles-pod
spec:
  test:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  containers:
    - name: dotfile-test-container
      image: registry.k8s.io/busybox
      abcd:
        - ls
        - "-l"
        - "/etc/secret-volume"
      volumeMount:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"